### ISSUE TITLE
pseudo class and pseudo element only selectors break scoped styles

### ISSUE THREAD

**Issue by kagankan** [withastro/compiler#706]
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows 11

## Current behavior

```astro
<a href=""></a>

<style>
  :any-link::after {
    content: "link";
  }
</style>
```

The style is converted to the CSS below:

```css
:any-link:after:where(.astro-RJEN7MQD){content:"link"}
```

The style is not applied to the `a` element.

## Expected behavior

```css
:any-link:where(.astro-RJEN7MQD):after{content:"link"}
/* or */
:where(.astro-RJEN7MQD):any-link:after{content:"link"}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bqgpy9?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
For reference, Svelte [converts](https://svelte.dev/repl/a837f421f37f4b50b9e94cccc01e545d?version=3.55.1) to something like `:where(.astro-RJEN7MQD):any-link:after{content:"link"}`, which I also think is the correct behaviour.

**Comment by jasikpark** [comment]
the problem here is that the scoped style class is selectively applied to elements depending on whether astro believes they will be styled, right? so if the `<a>` element got the class, it'd be fine

**Comment by bluwy** [comment]
The `<a>` element does get the class, but the generated scoped css doesn't reflect that:

```css
:any-link::after:where(.astro-RJEN7MQD){content:"link"}
```

The scoped class is targetting the `::after` pseudoselector instead of `:any-link`. And because there's no `astro-RJEN7MQD` attached to the pseudoselector (it can't have classes too), the style isn't applied properly.
